# Generated by Django 4.2.6 on 2023-10-23 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_subscription_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_valid',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 5, 40, 33, 246106)),
        ),
    ]
