# Generated by Django 4.2.6 on 2023-10-23 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_subscription_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 7, 15, 46, 226858)),
        ),
    ]
