# Generated by Django 4.2.6 on 2023-10-23 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_subscription_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateField(default=datetime.date(2023, 10, 22)),
        ),
    ]
