# Generated by Django 4.2.6 on 2023-10-25 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_subscription_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('clause', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateField(default=datetime.date(2023, 10, 24)),
        ),
    ]
