# Generated by Django 4.2.6 on 2023-11-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_screener_alter_user_subscription_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screener',
            name='clause',
        ),
        migrations.AddField(
            model_name='screener',
            name='cash_clause',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='screener',
            name='future_clause',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='screener',
            name='nifty_clause',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateField(default=datetime.date(2023, 11, 3)),
        ),
    ]
