# Generated by Django 4.2.6 on 2023-11-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_screener_clause_screener_cash_clause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screener',
            name='cash_clause',
        ),
        migrations.RemoveField(
            model_name='screener',
            name='future_clause',
        ),
        migrations.RemoveField(
            model_name='screener',
            name='nifty_clause',
        ),
    ]
